/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/JBNRZ/kubeovn-api/pkg/client/clientset/typed/kubeovn/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKubeovnV1 struct {
	*testing.Fake
}

func (c *FakeKubeovnV1) IPs() v2.IPInterface {
	return newFakeIPs(c)
}

func (c *FakeKubeovnV1) IPPools() v2.IPPoolInterface {
	return newFakeIPPools(c)
}

func (c *FakeKubeovnV1) IptablesDnatRules() v2.IptablesDnatRuleInterface {
	return newFakeIptablesDnatRules(c)
}

func (c *FakeKubeovnV1) IptablesEIPs() v2.IptablesEIPInterface {
	return newFakeIptablesEIPs(c)
}

func (c *FakeKubeovnV1) IptablesFIPRules() v2.IptablesFIPRuleInterface {
	return newFakeIptablesFIPRules(c)
}

func (c *FakeKubeovnV1) IptablesSnatRules() v2.IptablesSnatRuleInterface {
	return newFakeIptablesSnatRules(c)
}

func (c *FakeKubeovnV1) OvnDnatRules() v2.OvnDnatRuleInterface {
	return newFakeOvnDnatRules(c)
}

func (c *FakeKubeovnV1) OvnEips() v2.OvnEipInterface {
	return newFakeOvnEips(c)
}

func (c *FakeKubeovnV1) OvnFips() v2.OvnFipInterface {
	return newFakeOvnFips(c)
}

func (c *FakeKubeovnV1) OvnSnatRules() v2.OvnSnatRuleInterface {
	return newFakeOvnSnatRules(c)
}

func (c *FakeKubeovnV1) ProviderNetworks() v2.ProviderNetworkInterface {
	return newFakeProviderNetworks(c)
}

func (c *FakeKubeovnV1) QoSPolicies() v2.QoSPolicyInterface {
	return newFakeQoSPolicies(c)
}

func (c *FakeKubeovnV1) SecurityGroups() v2.SecurityGroupInterface {
	return newFakeSecurityGroups(c)
}

func (c *FakeKubeovnV1) Subnets() v2.SubnetInterface {
	return newFakeSubnets(c)
}

func (c *FakeKubeovnV1) SwitchLBRules() v2.SwitchLBRuleInterface {
	return newFakeSwitchLBRules(c)
}

func (c *FakeKubeovnV1) Vips() v2.VipInterface {
	return newFakeVips(c)
}

func (c *FakeKubeovnV1) Vlans() v2.VlanInterface {
	return newFakeVlans(c)
}

func (c *FakeKubeovnV1) Vpcs() v2.VpcInterface {
	return newFakeVpcs(c)
}

func (c *FakeKubeovnV1) VpcDnses() v2.VpcDnsInterface {
	return newFakeVpcDnses(c)
}

func (c *FakeKubeovnV1) VpcEgressGateways(namespace string) v2.VpcEgressGatewayInterface {
	return newFakeVpcEgressGateways(c, namespace)
}

func (c *FakeKubeovnV1) VpcNatGateways() v2.VpcNatGatewayInterface {
	return newFakeVpcNatGateways(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKubeovnV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
